# Copyright 2012 Rithis Studio LLC
# Author Vyacheslav Slinko <vyacheslav.slinko@rithis.com>

rithis_image_placeholder_full:
    pattern: /{x},{y},{backgroundColor},{textColor}
    defaults:
        _controller: RithisImagePlaceholderBundle:ImagePlaceholder:get
        y: ~
        backgroundColor: ~
        textColor: ~
    requirements:
        _method: GET
        x: '\d{1,3}'
        y: '\d{1,3}'
        backgroundColor: '[0-9a-fA-F]{6}'
        textColor: '[0-9a-fA-F]{6}'

rithis_image_placeholder_small:
    pattern: /{x},{backgroundColor},{textColor}
    defaults:
        _controller: RithisImagePlaceholderBundle:ImagePlaceholder:get
        y: ~
        backgroundColor: ~
        textColor: ~
    requirements:
        _method: GET
        x: '\d{1,3}'
        backgroundColor: '[0-9a-fA-F]{6}'
        textColor: '[0-9a-fA-F]{6}'
